/* automatically generated by rust-bindgen 0.58.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub type Height = u64;
    pub type Amount = u64;
    pub type AssetID = u32;
    pub type Timestamp = u64;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct Secp_point_data {
        pub X: [u8; 32usize],
        pub Y: u8,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct HeightPos {
        pub m_Height: root::Height,
        pub m_Pos: u32,
    }
    pub type PubKey = root::Secp_point_data;
    pub type ContractID = [u8; 32usize];
    pub type ShaderID = [u8; 32usize];
    pub type HashValue = [u8; 32usize];
    pub type HashValue512 = u8;
    pub type Secp_scalar_data = [u8; 32usize];
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct FundsChange {
        pub m_Amount: root::Amount,
        pub m_Aid: root::AssetID,
        pub m_Consume: u8,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SigRequest {
        pub m_pID: *const ::std::os::raw::c_void,
        pub m_nID: u32,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct HashObj {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct Secp_scalar {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct Secp_point {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct BlockHeader {
        pub _address: u8,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct BlockHeader_InfoBase {
        pub m_Timestamp: root::Timestamp,
        pub m_Kernels: root::HashValue,
        pub m_Definition: root::HashValue,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct BlockHeader_Info {
        pub _base: root::BlockHeader_InfoBase,
        pub m_Height: root::Height,
        pub m_Hash: root::HashValue,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct BlockHeader_Prefix {
        pub m_Height: root::Height,
        pub m_Prev: root::HashValue,
        pub m_ChainWork: root::HashValue,
    }
    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct BlockHeader_Element {
        pub _base: root::BlockHeader_InfoBase,
        pub m_PoW: root::BlockHeader_Element_PoW,
    }
    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct BlockHeader_Element_PoW {
        pub m_pIndices: [u8; 104usize],
        pub m_pNonce: [u8; 8usize],
        pub m_Difficulty: u32,
    }
    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct BlockHeader_Full {
        pub _base: root::BlockHeader_Prefix,
        pub _base_1: root::BlockHeader_Element,
    }
    extern "C" {
        #[link_name = "\u{1}get_Hash"]
        pub fn BlockHeader_Full_get_Hash(
            this: *const root::BlockHeader_Full,
            out: *mut root::HashValue,
            pRules: *const root::HashValue,
        );
    }
    extern "C" {
        #[link_name = "\u{1}get_HashInternal"]
        pub fn BlockHeader_Full_get_HashInternal(
            this: *const root::BlockHeader_Full,
            out: *mut root::HashValue,
            bFull: bool,
            pRules: *const root::HashValue,
        );
    }
    extern "C" {
        #[link_name = "\u{1}TestDifficulty"]
        pub fn BlockHeader_Full_TestDifficulty(this: *const root::BlockHeader_Full) -> bool;
    }
    impl BlockHeader_Full {
        #[inline]
        pub unsafe fn get_Hash(&self, out: *mut root::HashValue, pRules: *const root::HashValue) {
            BlockHeader_Full_get_Hash(self, out, pRules)
        }
        #[inline]
        pub unsafe fn get_HashInternal(
            &self,
            out: *mut root::HashValue,
            bFull: bool,
            pRules: *const root::HashValue,
        ) {
            BlockHeader_Full_get_HashInternal(self, out, bFull, pRules)
        }
        #[inline]
        pub unsafe fn TestDifficulty(&self) -> bool {
            BlockHeader_Full_TestDifficulty(self)
        }
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KeyTag {
        pub _address: u8,
    }
    pub const KeyTag_Internal: u8 = 0;
    pub const KeyTag_InternalStealth: u8 = 8;
    pub const KeyTag_LockedAmount: u8 = 1;
    pub const KeyTag_Refs: u8 = 2;
    pub const KeyTag_OwnedAsset: u8 = 3;
    pub const KeyTag_SidCid: u8 = 16;
    pub mod Merkle {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct Node {
            pub m_OnRight: u8,
            pub m_Value: root::HashValue,
        }
    }
    pub mod Env {
        #[allow(unused_imports)]
        use self::super::super::root;
        extern "C" {
            pub fn Memcpy(
                pDst: *mut ::std::os::raw::c_void,
                pSrc: *const ::std::os::raw::c_void,
                size: u32,
            ) -> *mut ::std::os::raw::c_void;
        }
        extern "C" {
            pub fn Memset(
                pDst: *mut ::std::os::raw::c_void,
                val: u8,
                size: u32,
            ) -> *mut ::std::os::raw::c_void;
        }
        extern "C" {
            pub fn Memcmp(
                p1: *const ::std::os::raw::c_void,
                p2: *const ::std::os::raw::c_void,
                size: u32,
            ) -> i32;
        }
        extern "C" {
            pub fn Memis0(p: *const ::std::os::raw::c_void, size: u32) -> u8;
        }
        extern "C" {
            pub fn Strlen(sz: *const ::std::os::raw::c_char) -> u32;
        }
        extern "C" {
            pub fn Strcmp(
                sz1: *const ::std::os::raw::c_char,
                sz2: *const ::std::os::raw::c_char,
            ) -> i32;
        }
        extern "C" {
            pub fn StackAlloc(size: u32) -> *mut ::std::os::raw::c_void;
        }
        extern "C" {
            pub fn StackFree(size: u32);
        }
        extern "C" {
            pub fn Heap_Alloc(size: u32) -> *mut ::std::os::raw::c_void;
        }
        extern "C" {
            pub fn Heap_Free(pPtr: *mut ::std::os::raw::c_void);
        }
        extern "C" {
            pub fn Halt();
        }
        extern "C" {
            pub fn HashWrite(
                pHash: *mut root::HashObj,
                p: *const ::std::os::raw::c_void,
                size: u32,
            );
        }
        extern "C" {
            pub fn HashGetValue(
                pHash: *mut root::HashObj,
                pDst: *mut ::std::os::raw::c_void,
                size: u32,
            );
        }
        extern "C" {
            pub fn HashFree(pHash: *mut root::HashObj);
        }
        extern "C" {
            pub fn get_Height() -> root::Height;
        }
        extern "C" {
            pub fn get_HdrInfo(hdr: *mut root::BlockHeader_Info);
        }
        extern "C" {
            pub fn get_HdrFull(hdr: *mut root::BlockHeader_Full);
        }
        extern "C" {
            pub fn get_RulesCfg(h: root::Height, res: *mut root::HashValue) -> root::Height;
        }
        extern "C" {
            pub fn HashCreateSha256() -> *mut root::HashObj;
        }
        extern "C" {
            pub fn HashCreateBlake2b(
                pPersonal: *const ::std::os::raw::c_void,
                nPersonal: u32,
                nResultSize: u32,
            ) -> *mut root::HashObj;
        }
        extern "C" {
            pub fn HashCreateKeccak(nBits: u32) -> *mut root::HashObj;
        }
        extern "C" {
            pub fn Secp_Scalar_alloc() -> *mut root::Secp_scalar;
        }
        extern "C" {
            pub fn Secp_Scalar_free(s: *mut root::Secp_scalar);
        }
        extern "C" {
            pub fn Secp_Scalar_import(
                s: *mut root::Secp_scalar,
                data: *const root::Secp_scalar_data,
            ) -> u8;
        }
        extern "C" {
            pub fn Secp_Scalar_export(
                s: *const root::Secp_scalar,
                data: *mut root::Secp_scalar_data,
            );
        }
        extern "C" {
            pub fn Secp_Scalar_neg(dst: *mut root::Secp_scalar, src: *const root::Secp_scalar);
        }
        extern "C" {
            pub fn Secp_Scalar_add(
                dst: *mut root::Secp_scalar,
                a: *const root::Secp_scalar,
                b: *const root::Secp_scalar,
            );
        }
        extern "C" {
            pub fn Secp_Scalar_mul(
                dst: *mut root::Secp_scalar,
                a: *const root::Secp_scalar,
                b: *const root::Secp_scalar,
            );
        }
        extern "C" {
            pub fn Secp_Scalar_inv(dst: *mut root::Secp_scalar, src: *const root::Secp_scalar);
        }
        extern "C" {
            pub fn Secp_Scalar_set(dst: *mut root::Secp_scalar, val: u64);
        }
        extern "C" {
            pub fn Secp_Point_alloc() -> *mut root::Secp_point;
        }
        extern "C" {
            pub fn Secp_Point_free(p: *mut root::Secp_point);
        }
        extern "C" {
            pub fn Secp_Point_Import(p: *mut root::Secp_point, pk: *const root::PubKey) -> u8;
        }
        extern "C" {
            pub fn Secp_Point_Export(p: *const root::Secp_point, pk: *mut root::PubKey);
        }
        extern "C" {
            pub fn Secp_Point_neg(dst: *mut root::Secp_point, src: *const root::Secp_point);
        }
        extern "C" {
            pub fn Secp_Point_add(
                dst: *mut root::Secp_point,
                a: *const root::Secp_point,
                b: *const root::Secp_point,
            );
        }
        extern "C" {
            pub fn Secp_Point_mul(
                dst: *mut root::Secp_point,
                p: *const root::Secp_point,
                s: *const root::Secp_scalar,
            );
        }
        extern "C" {
            pub fn Secp_Point_IsZero(p: *const root::Secp_point) -> u8;
        }
        extern "C" {
            pub fn Secp_Point_mul_G(dst: *mut root::Secp_point, s: *const root::Secp_scalar);
        }
        extern "C" {
            pub fn Secp_Point_mul_J(dst: *mut root::Secp_point, s: *const root::Secp_scalar);
        }
        extern "C" {
            pub fn Secp_Point_mul_H(
                dst: *mut root::Secp_point,
                s: *const root::Secp_scalar,
                aid: root::AssetID,
            );
        }
        extern "C" {
            pub fn VerifyBeamHashIII(
                pInp: *const ::std::os::raw::c_void,
                nInp: u32,
                pNonce: *const ::std::os::raw::c_void,
                nNonce: u32,
                pSol: *const ::std::os::raw::c_void,
                nSol: u32,
            ) -> u8;
        }
        extern "C" {
            pub fn LoadVar(
                pKey: *const ::std::os::raw::c_void,
                nKey: u32,
                pVal: *mut ::std::os::raw::c_void,
                nVal: u32,
                nType: u8,
            ) -> u32;
        }
        extern "C" {
            pub fn SaveVar(
                pKey: *const ::std::os::raw::c_void,
                nKey: u32,
                pVal: *const ::std::os::raw::c_void,
                nVal: u32,
                nType: u8,
            ) -> u32;
        }
        extern "C" {
            pub fn EmitLog(
                pKey: *const ::std::os::raw::c_void,
                nKey: u32,
                pVal: *const ::std::os::raw::c_void,
                nVal: u32,
                nType: u8,
            ) -> u32;
        }
        extern "C" {
            pub fn CallFar(
                cid: *const root::ContractID,
                iMethod: u32,
                pArgs: *mut ::std::os::raw::c_void,
                nArgs: u32,
                bInheritContext: u8,
            );
        }
        extern "C" {
            pub fn get_CallDepth() -> u32;
        }
        extern "C" {
            pub fn get_CallerCid(iCaller: u32, cid: *mut root::ContractID);
        }
        extern "C" {
            pub fn AddSig(pubKey: *const root::PubKey);
        }
        extern "C" {
            pub fn FundsLock(aid: root::AssetID, amount: root::Amount);
        }
        extern "C" {
            pub fn FundsUnlock(aid: root::AssetID, amount: root::Amount);
        }
        extern "C" {
            pub fn RefAdd(cid: *const root::ContractID) -> u8;
        }
        extern "C" {
            pub fn RefRelease(cid: *const root::ContractID) -> u8;
        }
        extern "C" {
            pub fn AssetCreate(pMeta: *const ::std::os::raw::c_void, nMeta: u32) -> root::AssetID;
        }
        extern "C" {
            pub fn AssetEmit(aid: root::AssetID, amount: root::Amount, bEmit: u8) -> u8;
        }
        extern "C" {
            pub fn AssetDestroy(aid: root::AssetID) -> u8;
        }
        extern "C" {
            pub fn Vars_Enum(
                pKey0: *const ::std::os::raw::c_void,
                nKey0: u32,
                pKey1: *const ::std::os::raw::c_void,
                nKey1: u32,
            ) -> u32;
        }
        extern "C" {
            pub fn Vars_MoveNext(
                iSlot: u32,
                pKey: *mut ::std::os::raw::c_void,
                nKey: *mut u32,
                pVal: *mut ::std::os::raw::c_void,
                nVal: *mut u32,
                nRepeat: u8,
            ) -> u8;
        }
        extern "C" {
            pub fn Vars_Close(iSlot: u32);
        }
        extern "C" {
            pub fn VarGetProof(
                pKey: *const ::std::os::raw::c_void,
                nKey: u32,
                ppVal: *mut *const ::std::os::raw::c_void,
                pnVal: *mut u32,
                ppProof: *mut *const root::Merkle::Node,
            ) -> u32;
        }
        extern "C" {
            pub fn Logs_Enum(
                pKey0: *const ::std::os::raw::c_void,
                nKey0: u32,
                pKey1: *const ::std::os::raw::c_void,
                nKey1: u32,
                pPosMin: *const root::HeightPos,
                pPosMax: *const root::HeightPos,
            ) -> u32;
        }
        extern "C" {
            pub fn Logs_MoveNext(
                iSlot: u32,
                pKey: *mut ::std::os::raw::c_void,
                nKey: *mut u32,
                pVal: *mut ::std::os::raw::c_void,
                nVal: *mut u32,
                pos: *mut root::HeightPos,
                nRepeat: u8,
            ) -> u8;
        }
        extern "C" {
            pub fn Logs_Close(iSlot: u32);
        }
        extern "C" {
            pub fn LogGetProof(
                pos: *const root::HeightPos,
                ppProof: *mut *const root::Merkle::Node,
            ) -> u32;
        }
        extern "C" {
            pub fn DerivePk(
                pubKey: *mut root::PubKey,
                pID: *const ::std::os::raw::c_void,
                nID: u32,
            );
        }
        extern "C" {
            pub fn DocAddGroup(szID: *const ::std::os::raw::c_char);
        }
        extern "C" {
            pub fn DocCloseGroup();
        }
        extern "C" {
            pub fn DocAddText(
                szID: *const ::std::os::raw::c_char,
                val: *const ::std::os::raw::c_char,
            );
        }
        extern "C" {
            pub fn DocAddNum32(szID: *const ::std::os::raw::c_char, val: u32);
        }
        extern "C" {
            pub fn DocAddNum64(szID: *const ::std::os::raw::c_char, val: u64);
        }
        extern "C" {
            pub fn DocAddArray(szID: *const ::std::os::raw::c_char);
        }
        extern "C" {
            pub fn DocCloseArray();
        }
        extern "C" {
            pub fn DocAddBlob(
                szID: *const ::std::os::raw::c_char,
                pBlob: *const ::std::os::raw::c_void,
                nBlob: u32,
            );
        }
        extern "C" {
            pub fn DocGetText(
                szID: *const ::std::os::raw::c_char,
                szRes: *mut ::std::os::raw::c_char,
                nLen: u32,
            ) -> u32;
        }
        extern "C" {
            pub fn DocGetNum32(szID: *const ::std::os::raw::c_char, pOut: *mut u32) -> u8;
        }
        extern "C" {
            pub fn DocGetNum64(szID: *const ::std::os::raw::c_char, pOut: *mut u64) -> u8;
        }
        extern "C" {
            pub fn DocGetBlob(
                szID: *const ::std::os::raw::c_char,
                pOut: *mut ::std::os::raw::c_void,
                nLen: u32,
            ) -> u32;
        }
        extern "C" {
            pub fn GenerateKernel(
                pCid: *const root::ContractID,
                iMethod: u32,
                pArg: *const ::std::os::raw::c_void,
                nArg: u32,
                pFunds: *const root::FundsChange,
                nFunds: u32,
                pSig: *const root::SigRequest,
                nSig: u32,
                szComment: *const ::std::os::raw::c_char,
                nCharge: u32,
            );
        }
    }
}
